version: '3.8'
services:
  backend:
    build: ./back
    ports:
      - "5000:5000"
    volumes:
      - ./back:/app
    environment:
      - FLASK_APP=app/getting_ranking.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development

  frontend:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
