"""Add today_yahoo_news table and todays_cnn_news table

Revision ID: 5019c3e76d98
Revises: 
Create Date: 2024-06-26 16:46:57.125074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5019c3e76d98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('today_cnn_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medium', sa.String(length='128'), nullable=False),
    sa.Column('news_data', sa.String(length='128'), nullable=False),
    sa.Column('news_url', sa.String(length='128'), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('today_yahoo_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medium', sa.String(length='128'), nullable=False),
    sa.Column('news_title', sa.String(length='128'), nullable=False),
    sa.Column('news_url', sa.String(length='128'), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('today_yahoo_db')
    op.drop_table('today_cnn_db')
    # ### end Alembic commands ###
